# Generated by Django 5.2.8 on 2025-11-12 08:52

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=files.models.document_upload_path),
        ),
    ]
